config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path('', include('messaging.messaging_app.urls', namespace='messaging_app'))
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

messaging/messaging_app/urls.py
import messaging_app.views as views

from django.urls import include, path, re_path

app_name = 'messaging_app'

urlpatterns = [

	path('login/', 
		views.Login.as_view(),
		 name='login'),

	path('logout/', 
		views.Logout.as_view(),
		 name='logout'),

	path('register-user/', 
		views.RegisterUser.as_view(),
		 name='register-user'),

	re_path(r'^employee/(?P<employee_id>\d+)/$', 
		views.EmployeeConversation.as_view(),
		 name='employee'),

	re_path(r'^conversation-detail/(?P<conversation_id>\d+)/$', 
		views.ConversationDetail.as_view(),
		 name='conversation-detail'),

	path('add-conversation/',
		views.AddConvesation.as_view(),
		 name='add-conversation'),

	re_path(r'^add-comment/(?P<conversation_id>\d+)/$', 
		views.AddComment.as_view(),
		 name='add-comment'),

	re_path(r'^update-comment/(?P<conversation_id>\d+)/(?P<comment_id>\d+)/$', 
		views.AddComment.as_view(),
		 name='update-comment'),

	re_path(r'^delete-comment/(?P<comment_id>\d+)/$', 
		views.DeleteComment.as_view(),
		 name='delete-comment'),

	path('', 
		views.Landing.as_view(),
		 name='landing'),
]

messaging/messaging_app/models.py
from django.db import models
from django.contrib.auth.models import User
from messaging.messaging_app.managers import *



class BaseModel(models.Model):

	class Meta:
		abstract = True
	
	objects			= BaseModelManager()
	created_by 		= models.ForeignKey(User, 
						related_name='%(app_label)s_%(class)s_creator',
						on_delete=models.CASCADE)
	created_on 		= models.DateTimeField(auto_now_add=True)
	modified_by 	= models.ForeignKey(User, 
						related_name='%(app_label)s_%(class)s_modifier',
						on_delete=models.CASCADE)
	modified_on		= models.DateTimeField(auto_now=True)
	deleted_by		= models.ForeignKey(User, null=True, blank=True, 
						related_name='%(app_label)s_%(class)s_deleter',
						on_delete=models.CASCADE)
	deleted_on		= models.DateTimeField(null=True, blank=True)
	is_deleted		= models.BooleanField(default=False)

	def save(self, *args, **kwargs):
	
		if not self.id or not self.created_on:
			self.created_on = timezone.now()
	
		return super(BaseModel,	self).save(*args, **kwargs)


class Employee(models.Model):

	RECRUITER_TYPE = (
		('R1', 'Primary Recruiter'),
		('R2', 'Secondary Recruiter')
	)

	employee 		= models.ForeignKey(User, on_delete=models.CASCADE)
	is_recruiter 	= models.BooleanField(default=False)
	is_candidate	= models.BooleanField(default=False)
	recruiter_type 	= models.CharField(max_length=2, choices=RECRUITER_TYPE,
						null=True, blank=True)

	def __str__(self):
		return self.employee.get_full_name()


class Conversation(BaseModel):

	sent_by 	= models.ForeignKey(User, related_name='sent_by',
					on_delete=models.CASCADE)
	sent_to		= models.ForeignKey(User, related_name='sent_to',
					on_delete=models.CASCADE)
	description = models.CharField(max_length=1024)

	def __str__(self):
		return self.sent_by.get_full_name()



class Comments(BaseModel):

	conversation 	= models.ForeignKey(Conversation, on_delete=models.CASCADE)
	comment 		= models.CharField(max_length=1024)

	def __str__(self):
		return self.comment

messaging/messaging_app/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import authenticate



class LoginForm(forms.Form):

	"""Standard username and password authentication form."""

	username = forms.CharField(label="Email address",
		error_messages={'required': "Please enter your username"})
	password = forms.CharField(label="Password", 
		widget=forms.PasswordInput, 
		error_messages={'required': "Please enter your password"})

	def __init__(self, *args, **kwargs):
		super(LoginForm, self).__init__(*args, **kwargs)


	def clean(self):
		"""
		Pass the provided username and password to the active
		authentication backends and verify the user account is
		not disabled. If authentication succeeds, the ``User`` object
		is assigned to the form so it can be accessed in the view.
		"""
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')

		username = username.lower()


		if username and password:
			try:
				self.user = authenticate(username=username, password=password)
			except Exception as e:
				error_msg = 'Internal error while authenticating user'
				raise forms.ValidationError(error_msg)

			if self.user is None:
				error_msg = 'The username or password is not correct'
				raise forms.ValidationError(error_msg)
			else:
				if not self.user.is_active:
					error_msg = 'This user account is disabled'
					raise forms.ValidationError(error_msg)

		return self.cleaned_data

messaging/messaging_app/views.py
import re
import uuid
import base64
import string
import random
import logging
import difflib
import mimetypes


from messaging.messaging_app.models import *
from messaging.messaging_app.utils import *
from messaging.messaging_app.forms import *
from messaging.messaging_app.send_email import send_email


from django.shortcuts import *
from django.conf import settings
from django.utils import timezone
from django.db.models import Value
from django.contrib import messages
from datetime import datetime, timedelta
from django.urls import reverse
from django.db.models.functions import Concat
from django.core.serializers import serialize
from django.core.exceptions import PermissionDenied
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View, TemplateView, FormView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseNotFound, JsonResponse
from django.contrib.staticfiles.templatetags.staticfiles import static


class EmployeeConversation(TemplateView):

	def get(self, request, employee_id, *args, **kwargs):

		try:
		
			self.template_name = 'messaging_app/conversions.html'

			context = dict()

			employee = Employee.objects.get(employee__id=employee_id)

			can_start_conversion = False
			can_delete_comment = False
			start_new = reverse('messaging_app:add-conversation')

			if employee.is_recruiter:
				can_start_conversion = True
				conversions = Conversation.objects.all()
			else:
				conversions = Conversation.objects.filter(sent_to=employee.employee)

			if employee.recruiter_type == 'R1':
				can_delete_comment = True

			context.update({
				'start_new': start_new,
				'conversions': conversions,
				'can_delete_comment': can_delete_comment,
				'can_start_conversion': can_start_conversion
			})

			return self.render_to_response(context)

		except Exception as e:
			print(e)
			raise Http404()


class Landing(TemplateView):

	def get(self, request, *args, **kwargs):

		self.template_name = 'messaging_app/homepage.html'

		context = dict()

		try:
			if request.user.is_authenticated:
				return redirect(reverse('messaging_app:employee', args=(request.user.id, )))
			else:
				print('redirect')
				return redirect(reverse('messaging_app:login'))

		except Exception as e:
			print(e)
			raise Http404()



class Login(TemplateView):

	form_class = LoginForm
	template_name = 'messaging_app/login.html'
	warning = ''

	def get(self, request, *args, **kwargs):

		self.template_name = 'messaging_app/login.html'

		action = reverse('messaging_app:login')

		context = {
			'action': action
		}

		storage = messages.get_messages(request)
		storage.used = True
		
		if request.user.is_authenticated:
			return redirect(reverse('messaging_app:landing'))

		return self.render_to_response(context)


	def post(self, request, *args, **kwargs):

		data = request.POST.dict()

		username = data.get('username')
		password = data.get('password')

		user = authenticate(request, username=username, password=password)

		context = dict()

		if user is not None:
			login(request, user)

			employee = Employee.objects.get(employee=user)
			
			return redirect(reverse('messaging_app:employee', args=(employee.id, )))
		else:
			return HttpResponse('Username or password is incorrect')



class Logout(View):

	@method_decorator(login_required)
	def get(self, request, *args, **kwargs):
		
		user = request.user

		if request.user.is_authenticated:
			logout(request)
		
		return redirect(reverse('messaging_app:login'))		



class RegisterUser(TemplateView):

	def get(self, request, *args, **kwargs):

		context = {
			'action': reverse('messaging_app:register-user')
		}

		self.template_name = 'messaging_app/signup.html'

		return self.render_to_response(context)

	def post(self, request, *args, **kwargs):

		try:

			data = request.POST.dict()

			context = dict()

			email = data.get('email')
			password = data.get('password')
			last_name = data.get('lastname')
			first_name = data.get('firstname')
			employee_type = data.get('employeeType')

			if not employee_type:
				return HttpResponse('Please select employee type')

			if not email:
				return HttpResponse('Please provide email address')

			if not first_name:
				return HttpResponse('Please provide first name')

			if not last_name:
				return HttpResponse('Please provide last name')

			if not password:
				return HttpResponse('Please provide password for the user')

			is_recruiter = False
			is_candidate = False
			recruiter_type = None

			if employee_type in ['R1', 'R2']:
				is_recruiter = True
				recruiter_type = employee_type
			else:
				is_candidate = True

			data = {
				'email': email,
				'username': email,
				'last_name': last_name,
				'first_name': first_name
			}

			if not User.objects.filter(email=email).exists():
				user = User.objects.create(**data)

				user.set_password(password)
				user.save()

				employee_data = {
					'employee': user,
					'is_recruiter': is_recruiter,
					'is_candidate': is_candidate,
					'recruiter_type': recruiter_type
				}

				employee = Employee.objects.create(**employee_data)

				return redirect(reverse('messaging_app:employee', args=(employee.id, )))

			else:
				return HttpResponse('Provided email address is already registered, Please provide a different email address')

			return redirect(reverse('hostel:landing'))

		except Exception as e:
			print(e)
			return HttpResponseNotFound('User could not be registered')



class ConversationDetail(TemplateView):

	def get(self, request, conversation_id, *args, **kwargs):
		
		try:
			self.template_name = 'messaging_app/conversation-detail.html'

			conversation = Conversation.objects.get(id=conversation_id)

			messages  = Comments.objects.filter(conversation=conversation)

			employee = Employee.objects.get(employee__id=request.user.id)

			can_start_conversion = False
			can_delete_comment = False
			start_new = reverse('messaging_app:add-conversation')

			if employee.is_recruiter:
				can_start_conversion = True
				conversions = Conversation.objects.all()
			else:
				conversions = Conversation.objects.filter(sent_to=employee.employee)

			if employee.recruiter_type == 'R1':
				can_delete_comment = True

			action = reverse('messaging_app:add-comment', args=(conversation.id, ))

			context = {
				'action': action,
				'messages': messages,
				'start_new': start_new,
				'conversions': conversions,
				'conversation': conversation,
				'can_delete_comment': can_delete_comment,
				'can_start_conversion': can_start_conversion
			}

			return self.render_to_response(context)

		except Exception as e:
			print(e)
			return HttpResponseNotFound('Comments could not fetched')



class AddConvesation(TemplateView):

	def get(self, request, *args, **kwargs):
		try:
			self.template_name = 'messaging_app/add-conversation.html'

			employees = Employee.objects.filter(is_candidate=True)

			context = {
				'employees': employees,
				'action': reverse('messaging_app:add-conversation')
			}

			return self.render_to_response(context)

		except Exception as e:
			return HttpResponseNotFound('New conversion could not be started')


	def post(self, request, *args, **kwargs):
		
		try:

			data = request.POST.dict()

			employee_id = int(data.get('employeeId'))
			description = data.get('description')

			sent_to = User.objects.get(id=employee_id)
			sent_by = request.user

			conversion_data = {
				'sent_to': sent_to,
				'sent_by': sent_by,
				'created_by': sent_by,
				'modified_by': sent_by,
				'description': description
			}

			conversion = Conversation.objects.create(**conversion_data)

			return redirect(reverse('messaging_app:conversation-detail', args=(conversion.id, )))

		except Exception as e:
			print(e)
			return HttpResponseNotFound('New conversion could not be started')



class AddComment(TemplateView):

	def get(self, request, conversation_id, comment_id=None, *args, **kwargs):

		try:
			self.template_name = 'messaging_app/update-comment.html'

			if comment_id:
				comment = Comments.objects.get(id=comment_id)
				action = reverse('messaging_app:update-comment', args=(comment.conversation.id, comment.id, ))
			else:
				comment = None
				action = reverse('messaging_app:add-comment', args=(comment.conversation.id, ))


			context = {
				'action': action,
				'comment': comment
			}

			return self.render_to_response(context)

		except Exception as e:
			print(e)
			return HttpResponseNotFound('Comment could not be added')

	
	def post(self, request, conversation_id, comment_id=None, *args, **kwargs):

		try:
			data = request.POST.dict()

			conversation = Conversation.objects.get(id=conversation_id)

			comment_text = data.get('comment')

			comment_data = {
				'comment': comment_text,
				'conversation': conversation,
				'created_by': request.user,
				'modified_by': request.user
			}

			if comment_id:
				comment = Comments.objects.get(id=comment_id)
				comment.comment = comment_text
				comment.modified_by = request.user
				comment.save()

			else:
				comment = Comments.objects.create(**comment_data)

			if not request.user == conversation.created_by:
				# This is not working
				sender = request.user.get_full_name()
				send_to = conversation.created_by.get_full_name()

				email_data = {
					'sender': sender,
					'send_to': send_to,
					'comment': comment,
					'sender_email':request.user.email,
					'receiver_email': conversation.created_by.email
				}

				try:
					send_email(email_data)
				except Exception as e:
					print(e)

			return redirect(reverse('messaging_app:conversation-detail', args=(conversation.id, )))

		except Exception as e:
			print(e)
			return HttpResponseNotFound('Comment could not be added')



class DeleteComment(View):

messaging/messaging_app/templates/messaging_app/add-conversation.html
{% extends 'messaging_app/base.html' %}
{% load static from staticfiles %}
{% load i18n %}
{% load l10n %}

{% block title %}New Conversation{% endblock title %}

{% block template %}

<div class="ui grid">
	<div class="three wide column"></div>
	<div class="ten wide column">
		<form class="ui add-conversation form" action="{{action}}" method="post">

			<h3 class="header">Conversation</h3>

			<div class="field">
				<label>Description</label>
				<input type="text" name="description" placeholder="description">
			</div>

			<div class="field">
				<div class="ui fluid selection dropdown employee">
					<i class="dropdown icon"></i>
					<span class="default text">Employee</span>
					<input type="hidden" name="employeeId">
					<div class="menu">
						{% for employee in employees %}
							<div class="item" data-value="{{employee.employee.id}}">
								{{employee.employee.get_full_name}}
							</div>
						{% endfor %}
					</div>
				</div>
			</div>

			{% csrf_token %}
			<button class="ui button" type="submit">Save</button>

			<div class="ui hidden divider"></div>
		</form>

	</div>
	<div class="three wide column"></div>
</div>

{% endblock template %}

{% block pagejs %}
	<script type="text/javascript">
		$form = $("div.messaging-wrapper").find("form.ui.form.add-conversation")
		initializeControls($form);
	</script>
{% endblock pagejs %}

messaging/messaging_app/templates/messaging_app/base.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block css %}
{% endblock css %}

{% block content %}

	<div class="messaging-wrapper">
		{% block template %}
		{% endblock template %}
	</div>

{% endblock %}

{% block jsdependencies %}
{% endblock jsdependencies %}


{% block javascript %}
	{% block pagejs %}{% endblock pagejs %}
{% endblock javascript %}

messaging/messaging_app/templates/messaging_app/conversation-detail.html
{% extends 'messaging_app/base.html' %}
{% load static from staticfiles %}
{% load i18n %}
{% load l10n %}

{% block title %}Conversation Detail{% endblock title %}

{% block template %}

<div class="ui grid">

	<div class="two wide column"></div>
	<div class="twelve wide column">
		<div class="ui comments">
			{% if messages %}
				{% for message in messages %}
					<div class="comment">

						<div class="content">
							<a class="author">{{message.created_by.get_full_name}}</a>
							<div class="metadata">
								<div class="date"></div>
							</div>
							<div class="text">
								{{message.comment}}
							</div>
							{% if can_delete_comment %}
								<a class="delete comment" title="Delete comment" href="{% url 'messaging_app:delete-comment' message.id %}">
								<i class="delete red icon"></i>

								<a class="edit comment" title="Edit comment" href="{% url 'messaging_app:update-comment' conversation.id message.id %}">
								<i class="pencil icon"></i>
							{% endif %}
						</div>
					</div>
				{% endfor %}
			{% else %}
				<div class="message">No comments found</div>
			{% endif %}
			<form class="ui reply form" action="{{action}}" method="post">
				<div class="field">
					<textarea name="comment"></textarea>
				</div>
				{% csrf_token %}
				<button class="ui button" type="submit">Save</button>
			</form>
		</div>
		
	</div>
	<div class="two wide column"></div>

</div>

{% endblock template %}

{% block pagejs %}
	<script type="text/javascript">
		deleteComment();
	</script>
{% endblock pagejs %}

messaging/messaging_app/templates/messaging_app/conversions.html
{% extends 'messaging_app/base.html' %}
{% load static from staticfiles %}
{% load i18n %}
{% load l10n %}

{% block title %}Conversations{% endblock title %}

{% block template %}

<div class="ui cards">
	{% if conversations %}
		{% for conversation in conversations %}
			<div class="card">
				<div class="content">
					<div class="header">{{conversation.sent_by.get_full_name}}</div>
					<div class="meta">{{conversation.sent_to.get_full_name}}</div>
					<div class="description">
					{{conversation.description}}
					</div>
				</div>
			</div>
		{% endfor %}
	{% else %}
		<br>
		<div class="message">No conversations found</div>

	{% endif %}

	{% if can_start_conversion %}
		<a href="{{start_new}}">Start New Coversation</a>
	{% endif %}

</div>

{% endblock template %}

{% block pagejs %}
{% endblock pagejs %}

messaging/messaging_app/templates/messaging_app/homepage.html
{% extends 'messaging_app/base.html' %}
{% load static from staticfiles %}
{% load i18n %}
{% load l10n %}

{% block title %}Login{% endblock title %}

{% block template %}
<div class="ui hidden divider"></div>
<div class="ui hidden divider"></div>
<div class="ui hidden divider"></div>
<div class="ui hidden divider"></div>
<div class="ui hidden divider"></div>
<div class="ui hidden divider"></div>
<div class="ui hidden divider"></div>
<div class="ui hidden divider"></div>
<div class="ui hidden divider"></div>
<div class="ui hidden divider"></div>

<div class="ui comments">
	{% for message in messages %}
		<div class="comment">

			<div class="content">
				<a class="author">{{message.created_by.get_full_name}}</a>
				<div class="metadata">
					<div class="date"></div>
				</div>
				<div class="text">
					{{message.comment}}
				</div>
				<div class="actions">
					<a class="reply">Reply</a>
				</div>
			</div>
		</div>
	{% enfor %}
	<form class="ui reply form">
		<div class="field">
			<textarea></textarea>
		</div>
		<div class="ui primary submit labeled icon button">
			<i class="icon edit"></i> Add Comment
		</div>
	</form>
</div>

{% endblock template %}

{% block pagejs %}
{% endblock pagejs %}

messaging/messaging_app/templates/messaging_app/login.html
{% extends 'messaging_app/base.html' %}
{% load static from staticfiles %}
{% load i18n %}
{% load l10n %}

{% block title %}Login{% endblock title %}

{% block template %}

<div class="ui grid">
	<div class="three wide column"></div>
	<div class="ten wide column">
		<form class="ui login form" action="{{action}}" method="post">

			<h3 class="header">Login Form</h3>

			<div class="field">
				<label>Email</label>
				<input type="text" name="username" placeholder="Email">
			</div>

			<div class="field">
				<label>Password</label>
				<input type="password" name="password" placeholder="Password">
			</div>
			{% csrf_token %}
			<button class="ui button" type="submit">Login</button>

			<a class="ui positive button" href="{% url 'messaging_app:register-user' %}">New to Messaging? Sign Up</a>

			<div class="ui hidden divider"></div>
		</form>

	</div>
	<div class="three wide column"></div>
</div>

{% endblock template %}

{% block pagejs %}
{% endblock pagejs %}

messaging/messaging_app/templates/messaging_app/signup.html
{% extends 'messaging_app/base.html' %}

{% load static from staticfiles %}
{% load i18n %}
{% load l10n %}

{% block title %}SignUp{% endblock title %}

{% block template %}

<div class="ui grid">

	<div class="three wide column"></div>

	<div class="ten wide column">

		<form class="ui form signup-form" action="{{action}}" method="post">

			<div class="two required fields">
				
				<div class="required field">
					<label for="firstname">First Name</label>
					<input type="text" name="firstname">
				</div>

				<div class="required field">
					<label for="lastname">Last Name</label>
					<input type="text" name="lastname">
				</div>

			</div>

			<div class="two required fields">

				<div class="required field">
					<label for="email">Email</label>
					<input type="text" name="email">
				</div>

				<div class="required field">
					<label for="password">Password</label>
					<input type="password" name="password">
				</div>

			</div>

			<div class="three fields">
				<div class="field">
					<div class="ui checkbox">
						<label>Candidate</label>
						<input type="radio" name="employeeType" value="candidate">
					</div>
				</div>

				<div class="field">
					<div class="ui checkbox">
						<label>Primary Recruiter</label>
						<input type="radio" name="employeeType" value="R1">
					</div>
				</div>

				<div class="field">
					<div class="ui checkbox">
						<label>Secondary Recruiter</label>
						<input type="radio" name="employeeType" value="R2">
					</div>
				</div>
			</div>

			<div class="ui hidden divider"></div>

			<div class="field">
				<input class="ui tiny uppercase positive action submit button" type="submit" value="{% trans 'Sign Up' %}">
				<input class="ui tiny uppercase negative action reset button" type="reset" value="{% trans 'Clear' %}">	
			</div>
			{% csrf_token %}
		</form>
	</div>

	<div class="three wide column"></div>
	
</div>


{% endblock template %}

{% block pagejs %}
	<script type="text/javascript">
		$form = $("div.messaging-wrapper").find("form.ui.form.signup-form")
		initializeControls($form);
	</script>
{% endblock pagejs %}

messaging/messaging_app/templates/messaging_app/update-comment.html
{% extends 'messaging_app/base.html' %}
{% load static from staticfiles %}
{% load i18n %}
{% load l10n %}

{% block title %}New Conversation{% endblock title %}

{% block template %}

<div class="ui grid">
	<div class="three wide column"></div>
	<div class="ten wide column">
		<form class="ui add-conversation form" action="{{action}}" method="post">

			<h3 class="header">Conversation</h3>

			<div class="field">
				<label>Comment</label>
				<input type="text" name="comment" placeholder="comment" {% if comment %} value="{{comment.comment}}" {% endif %}>
			</div>

			{% csrf_token %}
			<button class="ui button" type="submit">Save</button>

			<div class="ui hidden divider"></div>
		</form>

	</div>
	<div class="three wide column"></div>
</div>

{% endblock template %}

{% block pagejs %}
{% endblock pagejs %}